### ISSUE TITLE
Update vulkan_core.h in this repo from Vulkan-Headers

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/dfdutils#12]
Request per https://github.com/KhronosGroup/Vulkan-Docs/pull/2076#issuecomment-1474662663

**Comment by aharon-abramson** [comment]
Is someone going to be assigned to this issue?

**Comment by oddhack** [comment]
I created the issue per request from @MarkCallow whose repo this is, so I'm sure he's aware of it, but assigning him.

**Comment by aharon-abramson** [comment]
thank you

**Comment by MarkCallow** [comment]
Fixed by https://github.com/KhronosGroup/dfdutils/commit/854792a6ced4cb7cce64f26bf297bf7ea294a9b6.

Sorry for the long delay.
