### ISSUE TITLE
khr_df.h uses channelId but KDFS uses channelType.

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/dfdutils#14]
KDFS refers to the field in a sample identifying the type of channel as channelType both in text and in the non-normative C99 struct declaration. `khr_df.h` uses `KHR_DF_SAMPLE*_CHANNELID`. These should be changed to `KHR_DF_SAMPLE*_CHANNELTYPE`

**Comment by lexaknyazev** [comment]
It's slightly more complicated.

The DFD field is called `channelType` and it has 8 bits. The lower four bits contain the channel id and the top four bits contain the qualifiers.

**Comment by MarkCallow** [comment]
Oops. These defines specifically for the lower 4 bits of the channel type which is indeed the channel id.
